'use client';

import { motion } from 'framer-motion';
import { ArrowDownRight } from 'lucide-react';
import Image from 'next/image';
import { useRef } from 'react';

import heroModelImage from '@/public/images/hero-model.png';

import { Button } from '../ui/button';

export function HeroSection() {
  const containerRef = useRef<HTMLElement>(null);

  return (
    <section
      ref={containerRef}
      className="relative z-40 flex min-h-screen flex-col overflow-hidden bg-background pb-16 pt-32 sm:px-12 lg:px-20"
    >
      {/* Background Glows */}
      <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden">
        <div className="absolute right-0 top-0 h-[60vh] w-[60vw] rounded-full bg-aq-blue/5 opacity-50 mix-blend-multiply blur-3xl" />
        <div className="absolute bottom-10 left-10 h-[50vh] w-[50vw] rounded-full bg-purple-500/5 opacity-30 mix-blend-multiply blur-3xl" />
      </div>

      <div className="relative z-20 mx-auto flex w-full max-w-[1400px] flex-col-reverse items-center justify-between gap-12 lg:flex-row lg:items-end">
        {/* Left Column: Typography & CTA */}
        <div className="flex w-full flex-col items-start gap-10 lg:w-1/2 lg:pb-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-col gap-6"
          >
            <h1 className="font-display text-5xl font-bold leading-[1.1] tracking-tighter sm:text-6xl md:text-7xl lg:text-[5rem] xl:text-[6rem]">
              Skip the Studio. <br />
              <span className="font-serif font-light italic text-aq-blue">
                Ship the Collection.
              </span>
            </h1>

            <p className="max-w-md text-lg font-light leading-relaxed text-muted-foreground sm:text-xl md:text-2xl">
              Stop paying 5K–20K MAD for photoshoots. Anaqio's AI replaces
              expensive sets and models so you can launch your campaign today.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:gap-8"
          >
            <Button
              variant="brand"
              onClick={() =>
                document
                  .getElementById('waitlist')
                  ?.scrollIntoView({ behavior: 'smooth' })
              }
              className="group flex h-14 items-center gap-4 rounded-xl px-8 text-sm font-bold uppercase tracking-[0.2em] transition-all duration-300"
            >
              <span>Get Early Access</span>
              <div className="relative flex h-8 w-8 items-center justify-center overflow-hidden rounded-full bg-white/20 transition-colors group-hover:bg-white/30">
                <ArrowDownRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1 group-hover:translate-y-1" />
              </div>
            </Button>

            <div className="flex flex-col gap-1">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-aq-blue">
                Limited to 200 Brands
              </span>
              <span className="font-serif text-sm italic text-muted-foreground">
                Join in 30 seconds
              </span>
            </div>
          </motion.div>
        </div>

        {/* Right Column: Editorial Image */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
          className="relative w-full overflow-hidden rounded-2xl lg:w-1/2 lg:max-w-[600px]"
        >
          {/* Aspect ratio container */}
          <div
            className="relative w-full"
            style={{ paddingBottom: '125%' /* 4:5 aspect ratio */ }}
          >
            <Image
              src={heroModelImage}
              alt="Editorial fashion photography generated by Anaqio AI, featuring a model in a purple checkered suit"
              fill
              className="object-cover object-center"
              priority
              placeholder="blur"
              quality={85}
              sizes="(max-width: 1024px) 100vw, 50vw"
            />
            {/* Elegant overlay to blend the image into the light theme */}
            <div className="absolute inset-0 bg-gradient-to-t from-background/40 to-transparent" />
          </div>

          {/* Decorative Elements */}
          <div className="absolute left-6 top-6 z-10 flex items-center justify-between mix-blend-difference">
            <span className="font-mono text-xs tracking-widest text-white/70">
              AQ-AI-V1.0
            </span>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
