blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/anaqio/justwaitit/blob/develop/README.md
    about: Start here for setup instructions and project overview.
