import Link from 'next/link';

import type { Metadata } from 'next';

import { LegalPageLayout } from '@/components/layout/LegalPageLayout';

export const metadata: Metadata = {
  title: 'Terms of Service — Anaqio',
  description:
    'Terms of Service for Anaqio, a virtual studio for fashion commerce.',
};

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      eyebrow="Legal Framework"
      title="Terms of Service"
      effectiveDate="Effective: Feb 21, 2026"
      version="Version 1.0"
    >
      <div className="mb-12 rounded-r-xl border-l-2 border-aq-blue bg-secondary/30 p-6">
        <p className="text-sm leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Moroccan Law Compliance.</strong>{' '}
          These Terms of Service are governed by and construed in accordance
          with Moroccan law, including{' '}
          <strong className="text-aq-blue">Law No. 53-05</strong> on Electronic
          Exchange of Legal Data,{' '}
          <strong className="text-aq-blue">Law No. 31-08</strong> on Consumer
          Protection Measures, and the{' '}
          <strong className="text-foreground">
            Dahir des Obligations et Contrats (DOC)
          </strong>
          .
        </p>
      </div>

      <nav className="mb-16 rounded-2xl border border-border/50 bg-secondary/20 p-8">
        <h2 className="mb-6 text-sm font-bold uppercase tracking-widest text-foreground">
          Table of Contents
        </h2>
        <ol className="grid gap-3 text-sm">
          {[
            ['#acceptance', '1. Acceptance of Terms'],
            ['#definitions', '2. Definitions'],
            ['#service', '3. Description of Service'],
            ['#waitlist', '4. Waitlist & Pre-Launch'],
            ['#account', '5. Account Registration & Security'],
            ['#subscription', '6. Subscription & Billing'],
            ['#ip', '7. Intellectual Property'],
            ['#content', '8. User Content & AI Outputs'],
            ['#prohibited', '9. Prohibited Uses'],
            ['#warranties', '10. Disclaimers & Warranties'],
            ['#contact', '15. Contact'],
          ].map(([href, label]) => (
            <li key={href}>
              <a
                href={href}
                className="text-muted-foreground transition-colors hover:text-aq-blue"
              >
                {label}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      <article className="prose prose-invert prose-aq max-w-none space-y-16">
        <section id="acceptance">
          <h2 className="mb-6 font-display text-3xl font-bold tracking-tight">
            1. Acceptance of Terms
          </h2>
          <p className="mb-4 leading-relaxed text-muted-foreground">
            By accessing or using Anaqio&apos;s website, platform, mobile
            application, or any associated services (collectively, the{' '}
            <strong className="text-foreground">&quot;Service&quot;</strong>
            ), you confirm that you have read, understood, and agree to be bound
            by these Terms of Service (
            <strong className="text-foreground">&quot;Terms&quot;</strong>) and
            our{' '}
            <Link href="/privacy" className="text-aq-blue hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
          <p className="leading-relaxed text-muted-foreground">
            You must be at least{' '}
            <strong className="text-foreground">18 years of age</strong> to use
            Anaqio. By using the Service, you represent that you meet this
            minimum age requirement.
          </p>
        </section>

        <section id="definitions">
          <h2 className="mb-6 border-t border-border/30 pt-16 font-display text-3xl font-bold tracking-tight">
            2. Definitions
          </h2>
          <ul className="space-y-4">
            <li className="flex gap-4">
              <span className="font-bold text-aq-blue">01</span>
              <p className="text-muted-foreground">
                <strong className="text-foreground">&quot;Anaqio&quot;</strong>{' '}
                refers to Anaqio SARL, operator of the platform.
              </p>
            </li>
            <li className="flex gap-4">
              <span className="font-bold text-aq-blue">02</span>
              <p className="text-muted-foreground">
                <strong className="text-foreground">
                  &quot;AI Outputs&quot;
                </strong>{' '}
                means images, lookbooks, or other content generated by our
                models.
              </p>
            </li>
          </ul>
        </section>

        <section id="ip">
          <h2 className="mb-6 border-t border-border/30 pt-16 font-display text-3xl font-bold tracking-tight">
            7. Intellectual Property
          </h2>
          <h3 className="mb-4 text-xl font-semibold italic text-aq-purple">
            7.1 Anaqio&apos;s IP
          </h3>
          <p className="mb-6 leading-relaxed text-muted-foreground">
            All rights, title, and interest in the Service — including but not
            limited to the software, AI models, algorithms, and design — are
            owned by or licensed to Anaqio.
          </p>
          <div className="rounded-xl border border-aq-blue/20 bg-aq-blue/5 p-6">
            <h3 className="mb-2 text-sm font-bold uppercase tracking-widest text-aq-blue">
              Commercial Rights
            </h3>
            <p className="text-sm text-muted-foreground">
              You may use AI Outputs for commercial purposes consistent with
              your subscription plan. Anaqio does not claim ownership over AI
              Outputs generated from your unique inputs.
            </p>
          </div>
        </section>

        <section id="contact">
          <h2 className="mb-6 border-t border-border/30 pt-16 font-display text-3xl font-bold tracking-tight">
            15. Contact
          </h2>
          <div className="rounded-2xl border border-border/50 bg-secondary/50 p-8">
            <h3 className="mb-4 font-display text-xl font-bold">
              Anaqio — Legal Department
            </h3>
            <p className="mb-2 text-muted-foreground">
              Email:{' '}
              <a
                href="mailto:legal@anaqio.com"
                className="text-aq-blue hover:underline"
              >
                legal@anaqio.com
              </a>
            </p>
            <p className="mb-4 text-muted-foreground">
              Address: Casablanca, Morocco
            </p>
            <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">
              Response time: within 15 business days
            </p>
          </div>
        </section>
      </article>
    </LegalPageLayout>
  );
}
